#ifndef PAYLOAD_NAMES_H
#define PAYLOAD_NAMES_H

#define PAYLOAD_NAME_MQTT_RECEIVED_DATA "MQTT received data"
#define PAYLOAD_NAME_FILE_RECEIVED_DATA "File received data"
#define PAYLOAD_NAME_HTTP_RECEIVED_DATA "HTTP received data"
#define PAYLOAD_NAME_FILE_SEND_DATA "FILE_SEND_TEXT_DATA"
#define PAYLOAD_NAME_PROCESSING_ERROR "___processingError___"

#define PAYLOAD_MIMETYPE_APPLICATION_OCTET_STREAM "application/octet-stream"
#define PAYLOAD_MIMETYPE_TEXT_PLAIN "text/plain"

#define PAYLOAD_MATCHING_PATTERN_TRANSACTION_ID "transactionId"
#define PAYLOAD_MATCHING_PATTERN_DATE_CREATED "dateCreated"
#define PAYLOAD_MATCHING_PATTERN_TIME_CREATED "timeCreated"
#define PAYLOAD_MATCHING_PATTERN_DATA_ORIGIN "dataOrigin"
#define PAYLOAD_MATCHING_PATTERN_RECEIVED_BY_LISTENER "receivedByListener"
#define PAYLOAD_MATCHING_PATTERN_RECEIVED_VIA_PROTOCOL "receivedViaProtocol"
#define PAYLOAD_MATCHING_PATTERN_RECEIVED_FROM_HOST "receivedFomHost"
#define PAYLOAD_MATCHING_PATTERN_OUTPUT_FILE_NAME "outputFileName"
#define PAYLOAD_MATCHING_PATTERN_INPUT_FILE_NAME "inputFileName"

#define  PAYLOAD_MATCHING_PATTERN_VALUE_MQTT_LISTENER "MqttListener"
#define  PAYLOAD_MATCHING_PATTERN_VALUE_FILE_LISTENER "FileListener"
#define  PAYLOAD_MATCHING_PATTERN_VALUE_HTTP_LISTENER "HttpListener"
#define  PAYLOAD_MATCHING_PATTERN_VALUE_PROTOCOL_MQTT "mqtt"
#define  PAYLOAD_MATCHING_PATTERN_VALUE_PROTOCOL_FILE "file"
#define  PAYLOAD_MATCHING_PATTERN_VALUE_PROTOCOL_HTTP "http"
#endif //#ifndef PAYLOAD_NAMES_H