#ifndef PAYLOAD_NAMES_H
#define PAYLOAD_NAMES_H

#define PAYLOAD_NAME_MQTT_RECEIVED_DATA "MQTT received data"
#define PAYLOAD_NAME_PROCESSING_ERROR "___processingError___"

#define PAYLOAD_MIMETYPE_APPLICATION_OCTET_STREAM "application/octet-stream"
#define PAYLOAD_MIMETYPE_TEXT_PLAIN "text/plain"

#define PAYLOAD_MATCHIN_PATTERN_DATA_ORIGIN "data origin"
#define PAYLOAD_MATCHIN_PATTERN_RECEIVED_BY_LISTENER "received by listener"
#define PAYLOAD_MATCHIN_PATTERN_RECEIVED_VIA_PROTOCOL "received via protocol"
#define PAYLOAD_MATCHIN_PATTERN_RECEIVED_FROM_HOST "received from host"

#define  PAYLOAD_MATCHIN_PATTERN_VALUE_MQTT_LISTENER "MqttListener"
#define  PAYLOAD_MATCHIN_PATTERN_VALUE_PROTOCOL_MQTT "MQTT"
#endif //#ifndef PAYLOAD_NAMES_H